# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1611yOYEjmfkj84YydptQrRxy_7wEA1Xk
"""

import streamlit as st
import random

st.title('Test Streamlit')
st.write('Hello World!')
st.write('MADT4')

if st.button('Generate Random Number'):
    random_number = random.randint(1, 100)
    st.write(f'Random Number: {random_number}')